/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.test.chat;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JEditorPane;

/**
 *
 * @author yomna
 */
public class EditorPaneDemo extends javax.swing.JPanel {

    /**
     * Creates new form EditorPaneDemo
     */
    private String SenderName;
    private String message;
    private String time;
    private Font font;
    private Color color;
    private int size;
    Map<Color, String> colorMap = new HashMap<Color, String>();
    
    public EditorPaneDemo() {
        initComponents();
        jEditorPane1.setText("");
    }
    
    public EditorPaneDemo(String SenderName, String message, String time, Font font, Color color, int size) {
        
        this.SenderName = SenderName;
        this.message = message;
        this.time = time;
        this.font = font;
        this.color = color;
        this.size = size;
        String htmlfont = font.getFontName();
        initComponents();
        colorMap.put(Color.BLACK, "Black");   
        colorMap.put(Color.RED, "Red");
        colorMap.put(Color.GREEN, "Green");
        colorMap.put(Color.BLUE, "Blue");
        colorMap.put(Color.GRAY, "Gray");
        colorMap.put(Color.CYAN, "Cyan");
        String colorName = colorMap.get(color);
        String msg = "";
        String htmlTxt = "<html><body>"
                + "<FONT face="+htmlfont+" color="+colorName+" size="+size+"><b>"
                +SenderName+" : "+message+"</b><p align = right>"+time+"</p></FONT></body></html>";
        
        msg += htmlTxt;
        int red = color.getRed();
        int green = color.getGreen();
        int blue = color.getBlue();
        System.out.println(red);
        System.out.println(green);
        System.out.println(blue);
        jEditorPane1.setText(msg);
        jEditorPane1.setEditable(false);
        System.out.println(time);
        System.out.println("|||||||||||||||");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jEditorPane1.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
