/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chat.view;

import java.awt.Color;
import java.rmi.RemoteException;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.chat.controller.AuthenticationClientController;
import com.chat.model.User;
import com.chat.rmi.ChatClientService;
import com.chat.rmi.ChatServerService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author eltntawy
 */
public class SignInPanel extends javax.swing.JPanel {

    AuthenticationClientController signInController;
    JFrame parentFrame;

    /**
     * Creates new form TempletePanel
     */
    public SignInPanel(JFrame parentFrame, AuthenticationClientController signInController) {
        this.parentFrame = parentFrame;
        this.signInController = signInController;

        initComponents();
        setVisible(true);
        //  parentFrame.remove(parentFrame.getJMenuBar());

        txtUserName.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                TxtUserPassword.requestFocusInWindow();
                // btnLoginActionPerformed(e);
            }
        });

        TxtUserPassword.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                btnLoginActionPerformed(e);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new javax.swing.JPanel();
	lblLoginImg = new javax.swing.JLabel();
	lblPassword = new javax.swing.JLabel();
	lblForgetPassWord = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	btnLogin = new javax.swing.JButton();
	jLabel6 = new javax.swing.JLabel();
	lblUserName = new javax.swing.JLabel();
	txtUserName = new javax.swing.JTextField();
	TxtUserPassword = new javax.swing.JPasswordField();

	setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
	setMaximumSize(new java.awt.Dimension(300, 600));
	setMinimumSize(new java.awt.Dimension(300, 600));
	setPreferredSize(new java.awt.Dimension(300, 600));

	jPanel1.setMaximumSize(new java.awt.Dimension(315, 600));
	jPanel1.setMinimumSize(new java.awt.Dimension(315, 600));
	jPanel1.setPreferredSize(new java.awt.Dimension(315, 600));

	lblLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chat/view/resource/img/Login.png"))); // NOI18N
	lblLoginImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

	lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	lblPassword.setText("Password");

	lblForgetPassWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	lblForgetPassWord.setForeground(new java.awt.Color(102, 102, 102));
	lblForgetPassWord.setText("<html><u>Forget Password</u></html>");
	lblForgetPassWord.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		lblForgetPassWordMouseClicked(evt);
	    }
	});

	jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	jLabel5.setForeground(new java.awt.Color(102, 102, 102));
	jLabel5.setText("<html><u>Sign up</u></html>");
	jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		jLabel5MouseClicked(evt);
	    }
	});

	btnLogin.setText("Login");
	btnLogin.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		btnLoginActionPerformed(evt);
	    }
	});

	jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	jLabel6.setText("Not A Member ?");

	lblUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
	lblUserName.setText("User Name");

	txtUserName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
	txtUserName.setMaximumSize(new java.awt.Dimension(100, 30));
	txtUserName.setMinimumSize(new java.awt.Dimension(100, 30));
	txtUserName.setPreferredSize(new java.awt.Dimension(100, 30));

	TxtUserPassword.setMaximumSize(new java.awt.Dimension(100, 30));
	TxtUserPassword.setMinimumSize(new java.awt.Dimension(100, 30));
	TxtUserPassword.setPreferredSize(new java.awt.Dimension(100, 30));

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(lblForgetPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(62, 62, 62).addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(TxtUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))).addContainerGap()).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(lblLoginImg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap())));
	jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(277, 277, 277).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(lblForgetPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblUserName)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(TxtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnLogin))).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel6)).addGap(152, 152, 152)).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(lblLoginImg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(332, Short.MAX_VALUE))));

	add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void lblForgetPassWordMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblForgetPassWordMouseClicked
        // TODO add your handling code here:
        lblForgetPassWord.setFont(lblForgetPassWord.getFont().deriveFont(14f));
        lblForgetPassWord.setForeground(Color.DARK_GRAY);
    }// GEN-LAST:event_lblForgetPassWordMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        try {
            signInController.doSignUp();
        } catch (RemoteException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, " cannot sign up!!");
            e.printStackTrace();
        }
    }// GEN-LAST:event_jLabel5MouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        User user = null;
        try {
            user = signInController.doSignIn(txtUserName.getText(), new String(TxtUserPassword.getPassword()));

        } catch (RemoteException | SQLException e) {
            // TODO Auto-generated catch block

            e.printStackTrace();
        } finally {
            if (user == null) {
                JOptionPane.showMessageDialog(this, "Invalid User Name or Password !!");
                txtUserName.setText("");
                TxtUserPassword.setText("");
            }
        }

    }// GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtUserPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForgetPassWord;
    private javax.swing.JLabel lblLoginImg;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
