/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chat.view;

import com.chat.model.Message;
import com.chat.model.User;
import com.chat.view.renderer.ContactListCellRender;
import com.chat.view.resource.Resource;
import com.test.chat.EditorPaneDemo;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author yomna
 */
public class ChatFrame extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    private User Sender;
    private User Receiver;
    
    public ChatFrame() {
        initComponents();
        Message m = new Message("Yasmeen", "Marwa", "dfgdfgdfgdfg");
        Message m2 = new Message ("Mohammed", "Marwa","hhhhhhhh");
        Font f = new Font(Font.SERIF, Font.BOLD, 5);
        ConversationEditorPane sec = new ConversationEditorPane(m,f, Color.GREEN);
        jPanel1.add(sec,BorderLayout.CENTER);
        SenderPanel panel = new SenderPanel();
        panel.setSenderImagelbl(Resource.IMAGE_DEFAULT_USER);
        panel.setSenderNamelbl(m.getSenderName());
        jPanel3.add(panel);
        SenderPanel Rpanel = new SenderPanel();
        Rpanel.setSenderImagelbl(Resource.IMAGE_DEFAULT_USER);
        Rpanel.setSenderNamelbl(m.getReceiverName());
        jPanel3.add(Rpanel);
        /*DefaultListModel<User> listModel = new DefaultListModel<User>();
         listModel.addElement(new User("user name","name","",Resource.IMAGE_DEFAULT_USER,User.AVAILABLE));
         jList1.setCellRenderer(new ContactListCellRender());
         jList1.setModel(listModel);*/
    }

    public ChatFrame(User Sender, User Receiver) {
        this.Sender = Sender;
        this.Receiver = Receiver;
        initComponents();
        Font font = new Font( Font.SANS_SERIF, Font.ITALIC, 7);
        Message message = new Message (Sender.getUserName(), Receiver.getUserName(),"hjbiugoiuhiu gjhagdi" );
        ConversationEditorPane sec = new ConversationEditorPane(message,font, Color.BLUE);
        Message message2 = new Message (Sender.getUserName(), Receiver.getUserName(),"hjbiugoiuhiu" );
        sec.AppendText(message2, font, Color.yellow);
        jPanel1.add(sec,BorderLayout.CENTER);
        SenderPanel panel = new SenderPanel();
        panel.setSenderImagelbl(Sender.getUserPicture());
        panel.setSenderNamelbl(Sender.getUserName());
        jPanel3.add(panel);
        SenderPanel Rpanel = new SenderPanel();
        Rpanel.setSenderImagelbl(Receiver.getUserPicture());
        Rpanel.setSenderNamelbl(Receiver.getUserName());
        jPanel3.add(Rpanel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));

        jButton1.setText("Send");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("xdgdfjfgmnjhgf"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("dfgdfg"));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final JFrame f = new ChatFrame(new User("Youmna", "", "", Resource.IMAGE_AWAY, User.AVAILABLE),new User("Yasmeen", "", "", Resource.IMAGE_AVAILABLE, User.AWAY));
                
                try {

            //UIManager.setLookAndFeel("com.alee.laf.WebLookAndFeel");
                    //UIManager.installLookAndFeel("SeaGlass", "com.seaglasslookandfeel.SeaGlassLookAndFeel");
                    UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
                    //UIManager.setLookAndFeel(new SyntheticaWhiteVisionLookAndFeel());

                } catch (Exception e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

                SwingUtilities.invokeLater(new Runnable() {

                    public void run() {
                        // TODO Auto-generated method stub
                        SwingUtilities.updateComponentTreeUI(f);
                    }
                });

                f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
