/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chat.view;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author eltntawy
 */
public class ContactPanel extends javax.swing.JPanel {

    public String getStrUserName() {
        if (lblUserName != null) {
            return lblUserName.getText();
        }
        return null;
    }

    public void setStrUserName(String strUserName) {
        if (lblUserName != null) {
            this.lblUserName.setText(strUserName);
        }
    }

    public Icon getUserPicture() {;
        if (lblUserImage != null) {
            return lblUserImage.getIcon();
        }
        return null;
    }

    public void setUserPicture(Icon userPicture) {
        if (lblUserImage != null) {
            lblUserImage.setIcon(userPicture);
        }
    }

    public Icon getUserStatusImage() {
        if (lblUserStatus != null) {
            return lblUserImage.getIcon();
        }
        return null;
    }

    public void setUserStatusImage(Icon userStatusImage) {
        if(lblUserStatus != null ) 
            lblUserStatus.setIcon(userStatusImage);
    }

    /**
     * Creates new form ContactPanel
     */
    public ContactPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblUserImage = new javax.swing.JLabel();
        lblUserStatus = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(280, 50));
        setMinimumSize(new java.awt.Dimension(280, 50));
        setPreferredSize(new java.awt.Dimension(280, 50));

        lblUserName.setText("User Name");

        lblUserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chat/view/resource/img/messenger.png"))); // NOI18N

        lblUserStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chat/view/resource/img/status_online.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUserImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(lblUserStatus))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserImage)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(lblUserStatus))))
                .addContainerGap(2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserStatus;
    // End of variables declaration//GEN-END:variables
}
